spring:
  config:
    activate:
      on-profile: local

  application:
    name: NUNCHI

  web:
    resources:
      static-locations:
        - classpath:/static/front/
        - classpath:/templates_front/

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/nunchi
    username: nunchi
    password: nunchi1234
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        sslmode: disable

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

fastapi:
  base-url: http://localhost:8000

admin:
  password: ${ADMIN_PASSWORD:3316}

jwt:
  secret: ${JWT_SECRET:your-very-long-secret-key-your-very-long-secret-key}
  expiration-ms: 3600000